# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'bb1c8036-e45c-44d4-a1a7-8fa269f2afa2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName Proj1-repo -linkedTemplateUri https://raw.githubusercontent.com/padenom/Proj1-repo/master/CreateWebApp/linkedStorageAccount.json?token=AKP5COZ3UDT6XLVJFI2UHHC64KOGG'
    deploymentMode: 'Incremental'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'bb1c8036-e45c-44d4-a1a7-8fa269f2afa2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName Git_project -linkedTemplateUri https://raw.githubusercontent.com/padenom/AzureRmPipeline-repo/master/CreateWebApp/linkedStorageAccount.json?token=AKP5CO36GRQBEEQIPRZGDQ264J74O'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'